#!/usr/bin/env python3
"""
build_notebooks.py — generate the JupyterLab notebooks in notebooks/.

WHY A GENERATOR RATHER THAN HAND-WRITTEN .ipynb FILES
Notebooks are JSON. Editing them by hand is painful, and their diffs are
unreadable in git, which makes peer review of a notebook change nearly
impossible. Keeping the source here means the notebooks are regenerable and
this file is what gets reviewed.

THE TWO EXECUTION PATHS, AND HOW THEY STAY IN SYNC
  scripts/   the reproducible path. One command per stage, no hidden state.
             This is what a peer reviewer runs from a clean clone.
  notebooks/ the exploratory path. Same operations, broken into cells, with
             inspection points between them.

Both import every parameter from scripts/config.py. So the two paths can never
disagree about a threshold or a resolution -- only about presentation. If you
change an analysis decision, change it in config.py and both paths follow.

Run:  uv run tools/build_notebooks.py
"""

import json
from pathlib import Path

NB_DIR = Path(__file__).resolve().parent.parent / "notebooks"
NB_DIR.mkdir(exist_ok=True)

HEADER = [
    "import sys\n",
    "from pathlib import Path\n",
    "sys.path.insert(0, str(Path.cwd().parent / 'scripts'))\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import scanpy as sc\n",
    "import anndata as ad\n",
    "\n",
    "import config\n",
    "\n",
    "sc.settings.verbosity = 3\n",
    "sc.settings.figdir = config.FIG_DIR\n",
    "sc.settings.set_figure_params(dpi=100, facecolor='white', frameon=False)\n",
    "sc.logging.print_header()",
]


def md(*lines):
    return {"cell_type": "markdown", "metadata": {},
            "source": [l + "\n" for l in lines[:-1]] + [lines[-1]]}


def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": [l + "\n" for l in lines[:-1]] + [lines[-1]]}


def write(name, cells):
    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3 (project2)",
                           "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4, "nbformat_minor": 5,
    }
    (NB_DIR / name).write_text(json.dumps(nb, indent=1))
    print(f"  wrote notebooks/{name}")


# ======================================================================
# 01 — LOAD
# ======================================================================
write("01_load_data.ipynb", [
    md("# 01 — Load the eight samples",
       "",
       "Equivalent to `scripts/01_load_data.py`. Merges the 8 CellRanger outputs into one",
       "AnnData and attaches sex / treatment / replicate to every cell.",
       "",
       "**The critical part is the metadata.** If the labels are wrong here, everything",
       "downstream is wrong in a way that never raises an error."),
    code(*HEADER),
    md("## Find the sample folders"),
    code("sample_dirs = sorted(",
         "    p for p in config.DATA_DIR.iterdir()",
         "    if p.is_dir() and (p / 'matrix.mtx.gz').exists()",
         ")",
         "print(f'Found {len(sample_dirs)} samples:')",
         "for p in sample_dirs:",
         "    print(' ', p.name)"),
    md("## Load each one, attaching metadata",
       "",
       "`var_names='gene_symbols'` gives readable names (`repo`, `elav`, `ple`) rather than",
       "FlyBase IDs. If you end up with `FBgn...` names, the mitochondrial detection in",
       "step 02 silently finds nothing."),
    code("adatas = {}",
         "",
         "for path in sample_dirs:",
         "    name = path.name",
         "    sex, treatment, replicate = name.split('_')",
         "    assert sex in {'Female', 'Male'}, f'bad sex in {name}'",
         "    assert treatment in {'Cocaine', 'Sucrose'}, f'bad treatment in {name}'",
         "",
         "    a = sc.read_10x_mtx(path, var_names='gene_symbols', cache=True)",
         "    a.var_names_make_unique()",
         "",
         "    a.obs['sample'] = name",
         "    a.obs['sex'] = sex",
         "    a.obs['treatment'] = treatment",
         "    a.obs['replicate'] = replicate",
         "    a.obs['condition'] = f'{sex}_{treatment}'",
         "",
         "    print(f'{name}: {a.n_obs:,} cells x {a.n_vars:,} genes')",
         "    adatas[name] = a"),
    md("## Concatenate",
       "",
       "`join='outer'` keeps every gene seen in any sample. `join='inner'` would silently",
       "drop genes missing from a single sample — possibly a marker you need later.",
       "`index_unique='-'` stops identical barcodes from different runs colliding."),
    code("adata = ad.concat(adatas, label='sample_batch', index_unique='-', join='outer')",
         "adata.var_names_make_unique()",
         "",
         "for col in ['sample', 'sex', 'treatment', 'replicate', 'condition']:",
         "    adata.obs[col] = adata.obs[col].astype('category')",
         "",
         "print(f'Merged: {adata.n_obs:,} cells x {adata.n_vars:,} genes')",
         "adata"),
    md("## Check the design survived",
       "",
       "This should be a full 2×2×2. A missing cell in this table means a sample failed",
       "to load."),
    code("pd.crosstab(adata.obs['sex'], [adata.obs['treatment'], adata.obs['replicate']])"),
    code("adata.write(config.H5AD_RAW)",
         "print('Wrote', config.H5AD_RAW)"),
    md("---",
       "**Next:** run `tools/verify_sample_mapping.py` before going any further.",
       "It checks `roX1`/`roX2` to catch an inverted sex label. Then `02_qc_filter.ipynb`."),
])

# ======================================================================
# 02 — QC
# ======================================================================
write("02_qc_filter.ipynb", [
    md("# 02 — Quality control and filtering",
       "",
       "Equivalent to `scripts/02_qc_filter.py`. Produces **Figure 1** of the report.",
       "",
       "Droplet data contains three things that are not cells: empty droplets with ambient",
       "RNA (few genes), dying cells (high mitochondrial fraction), and doublets (two cells",
       "in one droplet, so too many genes). Each distorts clustering differently.",
       "",
       "**Look at the distributions before you cut.** Thresholds copied from a tutorial are",
       "not a justification you can defend at grading."),
    code(*HEADER),
    code("adata = sc.read_h5ad(config.H5AD_RAW)",
         "print(f'{adata.n_obs:,} cells x {adata.n_vars:,} genes')"),
    md("## Flag mitochondrial and ribosomal genes",
       "",
       "*Drosophila* naming is **not** the human convention — there is no `MT-` prefix.",
       "Mito genes are `mt:` (`mt:CoI`, `mt:ND1`, `mt:Cytb`); ribosomal proteins are",
       "`RpS`/`RpL`. Getting this wrong gives every cell 0% mt, you filter nothing, and",
       "nothing warns you."),
    code("adata.var['mt'] = adata.var_names.str.startswith('mt:')",
         "adata.var['ribo'] = adata.var_names.str.startswith(('RpS', 'RpL', 'rps', 'rpl'))",
         "",
         "print('mitochondrial genes:', int(adata.var['mt'].sum()))",
         "print('ribosomal genes:   ', int(adata.var['ribo'].sum()))",
         "",
         "assert adata.var['mt'].sum() > 0, (",
         "    'No mt: genes found — your var_names are probably FlyBase IDs. Redo step 01.')"),
    code("sc.pp.calculate_qc_metrics(",
         "    adata, qc_vars=['mt', 'ribo'], percent_top=None, log1p=False, inplace=True",
         ")",
         "adata.obs[['n_genes_by_counts', 'total_counts', 'pct_counts_mt']].describe().round(2)"),
    md("## Look before you cut"),
    code("sc.pl.violin(",
         "    adata,",
         "    ['n_genes_by_counts', 'total_counts', 'pct_counts_mt', 'pct_counts_ribo'],",
         "    groupby='condition', jitter=0.4, multi_panel=True, rotation=45,",
         ")"),
    code("sc.pl.scatter(adata, x='total_counts', y='n_genes_by_counts', color='pct_counts_mt')"),
    md("**Read these plots before continuing.**",
       "",
       "- Does the mt% distribution peak below 10? If it peaks above, a 10% cut throws",
       "  away real cells and you should raise it — and say so in Methods.",
       "- Does one sample look different from the others? That is a batch effect to",
       "  remember when you see the UMAP in step 03.",
       "- Where does the cloud of low-gene droplets end? That is your real `min_genes`."),
    code("# Per-sample summary — goes into the Methods section",
         "g = adata.obs.groupby('sample', observed=True)",
         "before = pd.DataFrame({",
         "    'n_cells': g.size(),",
         "    'median_genes': g['n_genes_by_counts'].median(),",
         "    'median_counts': g['total_counts'].median(),",
         "    'median_pct_mt': g['pct_counts_mt'].median(),",
         "}).round(2)",
         "before"),
    md("## Filter",
       "",
       "Thresholds come from `config.py`. Currently following the **paper's** Methods",
       "(300–2500 genes, min 5 cells per gene) rather than the guide's looser numbers,",
       "because RQ1 asks us to reproduce their 36 clusters."),
    code("print('min_genes    :', config.MIN_GENES_PER_CELL)",
         "print('max_genes    :', config.MAX_GENES_PER_CELL)",
         "print('min_cells    :', config.MIN_CELLS_PER_GENE)",
         "print('max_pct_mt   :', config.MAX_PCT_MT)"),
    code("n0 = adata.n_obs",
         "",
         "sc.pp.filter_cells(adata, min_genes=config.MIN_GENES_PER_CELL)",
         "print(f'after min_genes: {adata.n_obs:,}')",
         "",
         "if config.MAX_GENES_PER_CELL is not None:",
         "    adata = adata[adata.obs['n_genes_by_counts'] < config.MAX_GENES_PER_CELL].copy()",
         "    print(f'after max_genes (doublets): {adata.n_obs:,}')",
         "",
         "adata = adata[adata.obs['pct_counts_mt'] < config.MAX_PCT_MT].copy()",
         "print(f'after pct_mt: {adata.n_obs:,}')",
         "",
         "sc.pp.filter_genes(adata, min_cells=config.MIN_CELLS_PER_GENE)",
         "print(f'genes retained: {adata.n_vars:,}')",
         "",
         "print(f'\\nRetained {adata.n_obs:,}/{n0:,} cells ({100*adata.n_obs/n0:.1f}%)')",
         "print('Paper analysed 86,224 cells.')"),
    md("## Confirm the design is still balanced",
       "",
       "If one arm lost most of its cells, the DE comparison is compromised and you must",
       "say so in the report rather than present the design as intact."),
    code("adata.obs['condition'].value_counts().sort_index()"),
    code("sc.pl.violin(adata, ['n_genes_by_counts', 'total_counts', 'pct_counts_mt'],",
         "             groupby='condition', jitter=0.4, multi_panel=True, rotation=45)"),
    code("adata.write(config.H5AD_QC)",
         "print('Wrote', config.H5AD_QC)"),
])

# ======================================================================
# 03 — CLUSTER
# ======================================================================
write("03_normalize_cluster.ipynb", [
    md("# 03 — Normalization, dimensionality reduction, clustering",
       "",
       "Equivalent to `scripts/03_normalize_cluster.py`. Produces **Figure 2** and answers",
       "**Research Question 1**. This is the slow step: 20–60 minutes.",
       "",
       "## The one thing to understand here",
       "",
       "`adata.X` gets overwritten repeatedly. After scaling it holds z-scores, which are",
       "meaningless for differential expression — you cannot take a fold change of a",
       "z-score. So before scaling we stash the log-normalized matrix in `adata.raw`.",
       "Every DE call downstream must use `use_raw=True`.",
       "",
       "**This is the single most common bug in student scRNA-seq pipelines.** It produces",
       "plausible-looking numbers that are entirely wrong.",
       "",
       "## Memory (16 GB machine)",
       "",
       "Restart the kernel before running this notebook, and close other notebooks — a",
       "stale kernel holding a copy of `adata` is the usual cause of an OOM kill here."),
    code(*HEADER),
    code("import gc",
         "adata = sc.read_h5ad(config.H5AD_QC)",
         "print(f'{adata.n_obs:,} cells x {adata.n_vars:,} genes')"),
    md("## Normalize",
       "",
       "A cell with 20,000 UMIs is not expressing more than one with 5,000 — it was",
       "sequenced deeper. Scale every cell to the same total, then `log1p` to tame the long",
       "right tail so a 2-fold change means the same thing at high and low expression.",
       "",
       "The paper used **SCTransform** (regularized negative binomial) instead. That is a",
       "genuinely different variance model and is part of why your cluster count will",
       "differ from theirs. State it in Methods."),
    code("adata.layers['counts'] = adata.X.copy()   # keep integers for pseudobulk later",
         "",
         "sc.pp.normalize_total(adata, target_sum=config.TARGET_SUM)",
         "sc.pp.log1p(adata)",
         "",
         "adata.X = adata.X.astype('float32')   # halves memory, loses no real precision",
         "adata.raw = adata                     # full genes, log-normalized -> DE uses this"),
    md("## Highly variable genes",
       "",
       "Most of ~13,000 genes are uninformative noise for clustering. `batch_key='sample'`",
       "ranks genes by how *consistently* variable they are across samples, so one",
       "anomalous sample cannot drive the selection."),
    code("sc.pp.highly_variable_genes(",
         "    adata, n_top_genes=config.N_TOP_GENES,",
         "    batch_key=config.HVG_BATCH_KEY, flavor='seurat',",
         ")",
         "sc.pl.highly_variable_genes(adata)",
         "print(int(adata.var['highly_variable'].sum()), 'HVGs selected')"),
    md("Subsetting to HVGs **before** scaling is the key memory decision: `regress_out` and",
       "`scale` on 2,000 genes take minutes, on 13,000 they can exhaust 16 GB.",
       "`adata.raw` still holds all genes for DE."),
    code("adata = adata[:, adata.var['highly_variable']].copy()",
         "gc.collect()",
         "print(f'{adata.n_obs:,} cells x {adata.n_vars:,} genes')"),
    md("## Regress out technical covariates, then scale",
       "",
       "Slowest cell in the project. If the kernel dies here, set `REGRESS_OUT = False` in",
       "`config.py` — that is the largest single memory saving and the biology barely moves."),
    code("if config.REGRESS_OUT:",
         "    sc.pp.regress_out(adata, config.REGRESS_VARS)",
         "else:",
         "    print('Skipping regress_out (REGRESS_OUT=False)')",
         "",
         "sc.pp.scale(adata, max_value=config.SCALE_MAX_VALUE)",
         "gc.collect()"),
    md("## PCA",
       "",
       "Look at the elbow before accepting `N_PCS`. Components past the elbow are noise,",
       "and including them blurs cluster boundaries."),
    code("sc.tl.pca(adata, svd_solver='arpack', use_highly_variable=True,",
         "          random_state=config.RANDOM_SEED)",
         "sc.pl.pca_variance_ratio(adata, log=True, n_pcs=50)",
         "print('config.N_PCS =', config.N_PCS)"),
    md("## Neighbour graph and UMAP"),
    code("sc.pp.neighbors(adata, n_neighbors=config.N_NEIGHBORS, n_pcs=config.N_PCS,",
         "                random_state=config.RANDOM_SEED)",
         "sc.tl.umap(adata, random_state=config.RANDOM_SEED)"),
    md("## Resolution sweep — the honest answer to RQ1",
       "",
       "The paper justified resolution 0.8 by showing the cluster count plateaus there.",
       "Reproducing that curve is a much stronger result than a single number, and it is",
       "how you handle \"we got 31, not 36\" without either hiding it or tuning until it",
       "matches."),
    code("def run_leiden(adata, resolution, key):",
         "    try:",
         "        sc.tl.leiden(adata, resolution=resolution, key_added=key,",
         "                     flavor='igraph', n_iterations=2, directed=False,",
         "                     random_state=config.RANDOM_SEED)",
         "    except (TypeError, ValueError):",
         "        sc.tl.leiden(adata, resolution=resolution, key_added=key,",
         "                     random_state=config.RANDOM_SEED)",
         "    return adata.obs[key].nunique()",
         "",
         "sweep = []",
         "for res in config.RESOLUTION_SWEEP:",
         "    n = run_leiden(adata, res, f'leiden_sweep_{res}')",
         "    sweep.append({'resolution': res, 'n_clusters': n})",
         "    print(f'resolution {res}: {n} clusters')",
         "",
         "sweep_df = pd.DataFrame(sweep)",
         "sweep_df"),
    code("fig, ax = plt.subplots(figsize=(5, 3.5))",
         "ax.plot(sweep_df['resolution'], sweep_df['n_clusters'], 'o-')",
         "ax.axhline(config.TARGET_N_CLUSTERS, ls='--', c='crimson',",
         "           label=f'paper: {config.TARGET_N_CLUSTERS}')",
         "ax.set_xlabel('Leiden resolution'); ax.set_ylabel('clusters')",
         "ax.legend(frameon=False); fig.tight_layout()",
         "fig.savefig(config.FIG_DIR / '03_resolution_sweep.png', dpi=150)"),
    md("## Primary clustering at the paper's resolution"),
    code("n_main = run_leiden(adata, config.LEIDEN_RESOLUTION, config.LEIDEN_KEY)",
         "print(f'resolution {config.LEIDEN_RESOLUTION}: {n_main} clusters "
         "(paper: {config.TARGET_N_CLUSTERS})')"),
    code("sc.pl.umap(adata, color=[config.LEIDEN_KEY], legend_loc='on data', legend_fontsize=6)"),
    md("## Is there a batch effect?",
       "",
       "The paper reports no cluster was dominated by one sample. Even mixing across 8",
       "samples is 12.5% each. A cluster above ~40% from one sample is a batch effect, not",
       "a cell type — set `USE_HARMONY = True` in `config.py` and re-run."),
    code("sc.pl.umap(adata, color=['sex', 'treatment', 'condition', 'sample'], ncols=2)"),
    code("comp = pd.crosstab(adata.obs[config.LEIDEN_KEY], adata.obs['sample'], normalize='index')",
         "comp.max(axis=1).sort_values(ascending=False).head(10).round(3)"),
    code("sc.pl.umap(adata, color=['n_genes_by_counts', 'total_counts', 'pct_counts_mt'], ncols=3)"),
    code("adata.write(config.H5AD_CLUSTERED)",
         "print('Wrote', config.H5AD_CLUSTERED)"),
])

# ======================================================================
# 04 — ANNOTATE
# ======================================================================
write("04_annotate_clusters.ipynb", [
    md("# 04 — Cluster annotation",
       "",
       "Equivalent to `scripts/04_annotate_clusters.py`. Produces **Figure 3**.",
       "",
       "A cluster number means nothing. \"Cluster 14 responds strongly to cocaine\" is not a",
       "finding; \"Kenyon cells respond strongly to cocaine\" is. This step turns numbers",
       "into biology, and it requires **your judgement**, not a function call.",
       "",
       "## The warning that matters most",
       "",
       "The paper's C11 is Kenyon cells. **Your** cluster 11 is almost certainly something",
       "else — Leiden numbers clusters by size, and your clustering is not theirs. Match by",
       "**marker genes**, never by number. Writing \"our C11 agrees with their C11\" without",
       "checking markers is the error most likely to be caught in peer review."),
    code(*HEADER),
    code("adata = sc.read_h5ad(config.H5AD_CLUSTERED)",
         "print(f'{adata.n_obs:,} cells, {adata.obs[config.LEIDEN_KEY].nunique()} clusters')"),
    md("## Rank marker genes per cluster",
       "",
       "`use_raw=True` is essential: `adata.X` holds scaled z-scores restricted to 2,000",
       "HVGs. `adata.raw` holds log-normalized counts for all genes."),
    code("sc.tl.rank_genes_groups(adata, groupby=config.LEIDEN_KEY,",
         "                        method=config.DE_METHOD, use_raw=True, pts=True)",
         "",
         "markers = sc.get.rank_genes_groups_df(adata, group=None)",
         "markers.to_csv(config.TABLE_DIR / 'cluster_markers_all.csv', index=False)",
         "markers.head()"),
    code("for cl in sorted(adata.obs[config.LEIDEN_KEY].unique(), key=int):",
         "    top = markers[markers['group'] == cl].nlargest(5, 'scores')['names'].tolist()",
         "    n = int((adata.obs[config.LEIDEN_KEY] == cl).sum())",
         "    print(f'{cl:>3} (n={n:>6,}): ' + ', '.join(top))"),
    md("## Canonical marker panel",
       "",
       "Read this row by row:",
       "",
       "- `repo` high + `elav` low → **glia**",
       "- `elav` / `nSyb` / `brp` high → **neuron**",
       "- then subdivide neurons by neurotransmitter: `VAChT`, `Gad1`, `VGlut`, `ple`, `SerT`, `Tdc2`",
       "- `ey` + `Fas2` + `rut` → **Kenyon cells** (the mushroom body, the cocaine-relevant population)",
       "",
       "**Verify every marker against FlyBase before citing it.** Marker lists are a known",
       "AI hallucination risk, and the course policy puts validation on you."),
    code("var_groups = {}",
         "for cell_type, genes in config.CANONICAL_MARKERS.items():",
         "    present = [g for g in genes if g in adata.raw.var_names]",
         "    if present:",
         "        var_groups[cell_type] = present",
         "",
         "missing = [g for gs in config.CANONICAL_MARKERS.values() for g in gs",
         "           if g not in adata.raw.var_names]",
         "print('not found (check FlyBase spelling):', missing)"),
    code("sc.pl.dotplot(adata, var_names=var_groups, groupby=config.LEIDEN_KEY,",
         "              use_raw=True, standard_scale='var', dendrogram=True)"),
    code("sc.pl.matrixplot(adata, var_names=var_groups, groupby=config.LEIDEN_KEY,",
         "                 use_raw=True, standard_scale='var', dendrogram=True, cmap='viridis')"),
    code("key = [g for g in ['repo','elav','nSyb','ey','Fas2','VAChT','Gad1',",
         "                   'VGlut','ple','SerT','Tdc2','ninaE'] if g in adata.raw.var_names]",
         "sc.pl.umap(adata, color=key, ncols=4, use_raw=True)"),
    md("## Exact numbers, for the ambiguous clusters",
       "",
       "Reading values beats squinting at dot sizes when two clusters look similar."),
    code("flat = [g for gs in var_groups.values() for g in gs]",
         "expr = sc.get.obs_df(adata, keys=flat, use_raw=True)",
         "expr[config.LEIDEN_KEY] = adata.obs[config.LEIDEN_KEY].values",
         "mean_expr = expr.groupby(config.LEIDEN_KEY, observed=True).mean().round(3)",
         "mean_expr.to_csv(config.TABLE_DIR / 'marker_mean_expression_by_cluster.csv')",
         "mean_expr"),
    md("## Inspect one gene at a time",
       "",
       "Change `gene` and re-run while you work through the worksheet."),
    code("gene = 'ey'   # try: repo, alrm, moody, elav, Fas2, rut, VAChT, Gad1, VGlut, ple",
         "",
         "if gene in adata.raw.var_names:",
         "    sc.pl.umap(adata, color=gene, use_raw=True)",
         "    e = sc.get.obs_df(adata, keys=[gene], use_raw=True)",
         "    e[config.LEIDEN_KEY] = adata.obs[config.LEIDEN_KEY].values",
         "    display(e.groupby(config.LEIDEN_KEY, observed=True).mean()",
         "             .sort_values(gene, ascending=False).head(8))",
         "else:",
         "    print(f'{gene} not found')"),
    md("## The worksheet",
       "",
       "Deliberately blank. Filling it in **is** the intellectual work of this step, and you",
       "must be able to defend every label at grading."),
    code("counts = adata.obs[config.LEIDEN_KEY].value_counts().sort_index()",
         "worksheet = pd.DataFrame({",
         "    'cluster': counts.index,",
         "    'n_cells': counts.values,",
         "    'pct_of_total': (100 * counts.values / adata.n_obs).round(2),",
         "    'top_markers': [', '.join(markers[markers['group']==cl].nlargest(5,'scores')['names'])",
         "                    for cl in counts.index],",
         "    'cell_type_ANNOTATE_ME': '',",
         "    'paper_cluster_match': '',",
         "    'evidence_notes': '',",
         "})",
         "worksheet.to_csv(config.TABLE_DIR / 'annotation_worksheet.csv', index=False)",
         "worksheet"),
    md("**Now:** fill in `cell_type_ANNOTATE_ME` using the dotplots above and Supplemental",
       "Table S4 of the paper. Save as `annotation_worksheet_FILLED.csv` in the same folder,",
       "then run the next cell."),
    code("filled = config.TABLE_DIR / 'annotation_worksheet_FILLED.csv'",
         "",
         "if filled.exists():",
         "    ann = pd.read_csv(filled, dtype={'cluster': str})",
         "    mapping = dict(zip(ann['cluster'], ann['cell_type_ANNOTATE_ME']))",
         "    adata.obs['cell_type'] = (adata.obs[config.LEIDEN_KEY].astype(str)",
         "                              .map(mapping).fillna('Unannotated').astype('category'))",
         "    sc.pl.umap(adata, color='cell_type', legend_loc='on data', legend_fontsize=5)",
         "else:",
         "    adata.obs['cell_type'] = 'Unannotated'",
         "    print('Worksheet not filled in yet — saving with placeholder labels.')",
         "",
         "adata.write(config.H5AD_ANNOTATED)",
         "print('Wrote', config.H5AD_ANNOTATED)"),
])

# ======================================================================
# 05 — DE
# ======================================================================
write("05_de_analysis.ipynb", [
    md("# 05 — Differential expression",
       "",
       "Equivalent to `scripts/05_de_analysis.py`. Produces **Figure 4**, answers **RQ2 and RQ3**.",
       "",
       "Three levels, each answering something different:",
       "",
       "| | Question |",
       "|---|---|",
       "| **A** Global, per sex | do males respond more than females? (RQ3, magnitude) |",
       "| **B** Per cluster, per sex | which cell types respond? (RQ2) |",
       "| **C** Overlap between sexes | do they respond with the *same* genes? (RQ3, identity) |",
       "",
       "The project guide covers only **A**. But A alone cannot answer RQ2, and the paper's",
       "central claim — Kenyon cells and glia respond most — lives entirely in **B**.",
       "",
       "## A caveat to state in your report",
       "",
       "Wilcoxon across cells treats every cell as an independent replicate. They are not:",
       "cells from one fly brain are correlated, so p-values are anti-conservative and gene",
       "counts inflated. Notebook 05b cross-checks this. Report direction and relative",
       "magnitude confidently; treat absolute counts as approximate."),
    code(*HEADER),
    code("adata = sc.read_h5ad(config.H5AD_ANNOTATED)",
         "label_col = 'cell_type' if adata.obs['cell_type'].nunique() > 1 else config.LEIDEN_KEY",
         "print(f'{adata.n_obs:,} cells, labelling by {label_col!r}')"),
    md("## Helper functions",
       "",
       "`reference='Sucrose'` makes sucrose the denominator, so **positive log2FC = up in",
       "cocaine**. Get this backwards and every biological statement in your Discussion",
       "inverts."),
    code("def de_cocaine_vs_sucrose(subset):",
         "    sc.tl.rank_genes_groups(subset, groupby='treatment', reference='Sucrose',",
         "                            method=config.DE_METHOD, use_raw=True, pts=True)",
         "    df = sc.get.rank_genes_groups_df(subset, group='Cocaine')",
         "    return df.dropna(subset=['logfoldchanges', 'pvals_adj'])",
         "",
         "def significant(df, lfc=config.LOG2FC_THRESHOLD):",
         "    return df[(df['logfoldchanges'].abs() > lfc) &",
         "              (df['pvals_adj'] < config.PADJ_THRESHOLD)]"),
    md("## A. Global DE per sex",
       "",
       "**On units:** scanpy reports log2 fold change; the paper reports natural log.",
       "The paper's `|ln FC| > 1` equals `|log2FC| > 1.44` — *stricter* than the guide's 1.0.",
       "We report both so the comparison is honest."),
    code("results = {}",
         "",
         "for sex in ['Male', 'Female']:",
         "    sub = adata[adata.obs['sex'] == sex].copy()",
         "    df = de_cocaine_vs_sucrose(sub)",
         "    results[sex] = df",
         "    df.to_csv(config.TABLE_DIR / f'de_global_{sex.lower()}_all.csv', index=False)",
         "",
         "    sig = significant(df)",
         "    sig_paper = significant(df, config.PAPER_EQUIVALENT_LOG2FC)",
         "    print(f'{sex}: {sub.n_obs:,} cells')",
         "    print(f'  guide threshold (|log2FC|>1.0): {len(sig)} genes '",
         "          f'({int((sig.logfoldchanges>0).sum())} up, {int((sig.logfoldchanges<0).sum())} down)')",
         "    print(f'  paper equivalent (|log2FC|>1.44): {len(sig_paper)} genes')",
         "    del sub"),
    code("m = len(significant(results['Male']))",
         "f = len(significant(results['Female']))",
         "print(f'Male:Female ratio = {m}:{f}' + (f' ({m/f:.2f}x)' if f else ''))",
         "print('Paper: 691 vs 322 (~2.1x) at their own thresholds.')",
         "print('The RATIO is the reproducible claim; absolute counts depend on')",
         "print('normalization, thresholds and test choice, all of which differ here.')"),
    md("### Volcano plots"),
    code("def volcano(df, title, n_label=12):",
         "    d = df.copy()",
         "    d['neglog10p'] = -np.log10(d['pvals_adj'].clip(lower=1e-300))",
         "    sig = ((d['pvals_adj'] < config.PADJ_THRESHOLD) &",
         "           (d['logfoldchanges'].abs() > config.LOG2FC_THRESHOLD))",
         "",
         "    fig, ax = plt.subplots(figsize=(6.5, 5))",
         "    ax.scatter(d.loc[~sig,'logfoldchanges'], d.loc[~sig,'neglog10p'],",
         "               s=4, c='lightgrey', rasterized=True)",
         "    up, dn = sig & (d.logfoldchanges > 0), sig & (d.logfoldchanges < 0)",
         "    ax.scatter(d.loc[up,'logfoldchanges'], d.loc[up,'neglog10p'], s=6,",
         "               c='crimson', label=f'up ({int(up.sum())})', rasterized=True)",
         "    ax.scatter(d.loc[dn,'logfoldchanges'], d.loc[dn,'neglog10p'], s=6,",
         "               c='steelblue', label=f'down ({int(dn.sum())})', rasterized=True)",
         "    for _, r in d[sig].nlargest(n_label, 'neglog10p').iterrows():",
         "        ax.annotate(r['names'], (r.logfoldchanges, r.neglog10p), fontsize=6)",
         "    ax.axhline(-np.log10(config.PADJ_THRESHOLD), ls='--', lw=.7, c='k')",
         "    ax.axvline(config.LOG2FC_THRESHOLD, ls='--', lw=.7, c='k')",
         "    ax.axvline(-config.LOG2FC_THRESHOLD, ls='--', lw=.7, c='k')",
         "    ax.set_xlabel('log2FC (Cocaine / Sucrose)'); ax.set_ylabel('-log10 padj')",
         "    ax.set_title(title, fontsize=10); ax.legend(frameon=False, fontsize=8)",
         "    fig.tight_layout()",
         "    return fig",
         "",
         "for sex in ['Male', 'Female']:",
         "    fig = volcano(results[sex], f'{sex}: cocaine vs sucrose')",
         "    fig.savefig(config.FIG_DIR / f'05_volcano_{sex.lower()}.png', dpi=150)",
         "    plt.show()"),
    md("## B. Per-cluster DE — this is RQ2",
       "",
       "Slow: one Wilcoxon test per cluster per sex. Clusters with fewer than",
       "`MIN_CELLS_PER_GROUP_FOR_DE` cells in either arm are skipped, because Wilcoxon on",
       "4 cells produces noise, not biology."),
    code("per_cluster, per_cluster_genes = [], []",
         "clusters = sorted(adata.obs[label_col].unique(), key=str)",
         "",
         "for sex in ['Male', 'Female']:",
         "    sex_data = adata[adata.obs['sex'] == sex]",
         "    for cl in clusters:",
         "        sub = sex_data[sex_data.obs[label_col] == cl].copy()",
         "        counts = sub.obs['treatment'].value_counts()",
         "        if min(counts.get('Cocaine', 0), counts.get('Sucrose', 0)) < config.MIN_CELLS_PER_GROUP_FOR_DE:",
         "            per_cluster.append({'sex': sex, 'cluster': cl, 'n_cells': sub.n_obs,",
         "                                'n_sig': np.nan, 'note': 'too few cells'})",
         "            del sub; continue",
         "        try:",
         "            df = de_cocaine_vs_sucrose(sub)",
         "        except Exception as e:",
         "            per_cluster.append({'sex': sex, 'cluster': cl, 'n_cells': sub.n_obs,",
         "                                'n_sig': np.nan, 'note': str(e)})",
         "            del sub; continue",
         "        sig = significant(df)",
         "        per_cluster.append({'sex': sex, 'cluster': cl, 'n_cells': sub.n_obs,",
         "                            'n_sig': len(sig),",
         "                            'n_up': int((sig.logfoldchanges > 0).sum()),",
         "                            'n_down': int((sig.logfoldchanges < 0).sum()), 'note': ''})",
         "        if len(sig):",
         "            s = sig.copy(); s['sex'], s['cluster'] = sex, cl",
         "            per_cluster_genes.append(s)",
         "        del sub",
         "    print(f'{sex}: done')",
         "",
         "pc = pd.DataFrame(per_cluster)",
         "pc.to_csv(config.TABLE_DIR / 'de_per_cluster_summary.csv', index=False)",
         "if per_cluster_genes:",
         "    pd.concat(per_cluster_genes, ignore_index=True).to_csv(",
         "        config.TABLE_DIR / 'de_per_cluster_significant_genes.csv', index=False)"),
    code("ranked = (pc.dropna(subset=['n_sig']).groupby('cluster', observed=True)['n_sig']",
         "            .sum().sort_values(ascending=False))",
         "print('Most cocaine-responsive clusters:')",
         "print(ranked.head(10).to_string())",
         "print()",
         "print('Paper: Kenyon cells (C11), astrocytes (C17), surface glia (C22),')",
         "print('and unannotated C16 were their strongest responders.')",
         "print('Match by CELL TYPE, not cluster number.')"),
    code("pivot = pc.pivot_table(index='cluster', columns='sex', values='n_sig').fillna(0)",
         "fig, ax = plt.subplots(figsize=(5, max(4, 0.25*len(pivot))))",
         "im = ax.imshow(pivot.values, aspect='auto', cmap='magma')",
         "ax.set_xticks(range(len(pivot.columns))); ax.set_xticklabels(pivot.columns)",
         "ax.set_yticks(range(len(pivot.index)))",
         "ax.set_yticklabels(pivot.index, fontsize=6)",
         "ax.set_title('Significant DE genes per cluster', fontsize=10)",
         "fig.colorbar(im, ax=ax, label='n DE genes'); fig.tight_layout()",
         "fig.savefig(config.FIG_DIR / '05_de_burden_heatmap.png', dpi=150)"),
    md("## C. Sexual dimorphism — shared vs distinct",
       "",
       "The paper's subtler point: some shared genes move in **opposite directions** between",
       "sexes. That is stronger evidence of dimorphism than counts alone."),
    code("male_sig, female_sig = significant(results['Male']), significant(results['Female'])",
         "ms, fs = set(male_sig['names']), set(female_sig['names'])",
         "shared = ms & fs",
         "",
         "print(f'male only:   {len(ms - fs)}')",
         "print(f'female only: {len(fs - ms)}')",
         "print(f'shared:      {len(shared)}')"),
    code("if shared:",
         "    cmp = pd.DataFrame({",
         "        'male_log2FC': male_sig.set_index('names')['logfoldchanges'][list(shared)],",
         "        'female_log2FC': female_sig.set_index('names')['logfoldchanges'][list(shared)],",
         "    })",
         "    cmp['opposite'] = np.sign(cmp.male_log2FC) != np.sign(cmp.female_log2FC)",
         "    cmp.to_csv(config.TABLE_DIR / 'de_shared_genes_direction.csv')",
         "    print(f'{int(cmp.opposite.sum())} shared genes change in OPPOSITE directions')",
         "",
         "    fig, ax = plt.subplots(figsize=(5, 5))",
         "    ax.scatter(cmp.male_log2FC, cmp.female_log2FC, s=14,",
         "               c=np.where(cmp.opposite, 'crimson', 'grey'))",
         "    lim = float(np.nanmax(np.abs(cmp[['male_log2FC','female_log2FC']].values))) * 1.1",
         "    ax.plot([-lim, lim], [-lim, lim], ls='--', lw=.7, c='k')",
         "    ax.axhline(0, lw=.5, c='k'); ax.axvline(0, lw=.5, c='k')",
         "    ax.set_xlabel('male log2FC'); ax.set_ylabel('female log2FC')",
         "    fig.tight_layout()",
         "    fig.savefig(config.FIG_DIR / '05_sex_concordance.png', dpi=150)",
         "    display(cmp.sort_values('opposite', ascending=False).head(15).round(3))"),
    md("## D. Positive control",
       "",
       "Genes the paper names explicitly. If **none** of these move at all, suspect a",
       "pipeline error before you conclude the paper was wrong."),
    code("watch = (config.PAPER_CORE_RESPONSE_GENES['up'] +",
         "         config.PAPER_CORE_RESPONSE_GENES['down'] +",
         "         config.PAPER_DISCUSSION_GENES)",
         "",
         "rows = []",
         "for sex in ['Male', 'Female']:",
         "    d = results[sex].set_index('names')",
         "    for g in watch:",
         "        if g in d.index:",
         "            r = d.loc[g]",
         "            rows.append({'gene': g, 'sex': sex,",
         "                         'log2FC': round(float(r.logfoldchanges), 3),",
         "                         'padj': float(r.pvals_adj)})",
         "",
         "chk = pd.DataFrame(rows)",
         "chk.to_csv(config.TABLE_DIR / 'paper_gene_check.csv', index=False)",
         "chk.pivot_table(index='gene', columns='sex', values='log2FC').round(2)"),
])

# ======================================================================
# 05b — PSEUDOBULK
# ======================================================================
write("05b_pseudobulk_check.ipynb", [
    md("# 05b — Pseudobulk validation",
       "",
       "Equivalent to `scripts/05b_pseudobulk_check.py`. Not in the project guide — added",
       "because it is the honest answer to the main statistical criticism of notebook 05.",
       "",
       "## The problem",
       "",
       "Notebook 05 ran Wilcoxon across ~80,000 cells, a test that assumes cells are",
       "independent replicates. They are not: all cells in `Male_Cocaine_1` came from one",
       "pool of 20 brains processed together. Treating them as 10,000 independent",
       "observations is **pseudoreplication**, and it is the single most-cited criticism of",
       "scRNA-seq differential expression.",
       "",
       "## The check",
       "",
       "Sum counts per sample → one profile per biological replicate → test 2 vs 2.",
       "With n=2 this is badly underpowered, so **few significant genes is expected and is",
       "not a failure**. What we check is whether the *direction* of change agrees.",
       "High concordance means the cell-level result reflects real biology.",
       "",
       "Being able to say this in your Discussion and your rebuttal shows you understand",
       "the statistics rather than just the API."),
    code(*HEADER),
    code("from scipy import stats",
         "",
         "adata = sc.read_h5ad(config.H5AD_ANNOTATED)",
         "print(f'{adata.n_obs:,} cells')"),
    md("## Build the pseudobulk matrix"),
    code("counts = adata.layers['counts'] if 'counts' in adata.layers else adata.raw.X",
         "genes = adata.var_names if 'counts' in adata.layers else adata.raw.var_names",
         "",
         "rows, meta = [], []",
         "for sample in adata.obs['sample'].cat.categories:",
         "    mask = (adata.obs['sample'] == sample).values",
         "    if mask.sum() == 0: continue",
         "    rows.append(np.asarray(counts[mask].sum(axis=0)).ravel())",
         "    o = adata.obs.loc[mask].iloc[0]",
         "    meta.append({'sample': sample, 'sex': o['sex'],",
         "                 'treatment': o['treatment'], 'n_cells': int(mask.sum())})",
         "",
         "pb = pd.DataFrame(np.vstack(rows), index=[m['sample'] for m in meta], columns=genes)",
         "meta = pd.DataFrame(meta).set_index('sample')",
         "meta"),
    code("pb = pb.loc[:, pb.sum(axis=0) >= 50]   # drop negligible genes",
         "lcpm = np.log2(pb.div(pb.sum(axis=1), axis=0) * 1e6 + 1)",
         "print(f'{pb.shape[1]:,} genes kept')"),
    md("## Test, 2 vs 2 per sex"),
    code("def bh(p):",
         "    p = np.nan_to_num(p, nan=1.0)",
         "    order = np.argsort(p)",
         "    ranked = p[order] * len(p) / (np.arange(len(p)) + 1)",
         "    out = np.empty_like(ranked)",
         "    out[order] = np.minimum.accumulate(ranked[::-1])[::-1].clip(max=1.0)",
         "    return out",
         "",
         "pb_results = {}",
         "for sex in ['Male', 'Female']:",
         "    idx = meta.index[meta['sex'] == sex]",
         "    coc = [s for s in idx if meta.loc[s, 'treatment'] == 'Cocaine']",
         "    suc = [s for s in idx if meta.loc[s, 'treatment'] == 'Sucrose']",
         "    a, b = lcpm.loc[coc], lcpm.loc[suc]",
         "    lfc = a.mean(axis=0) - b.mean(axis=0)",
         "    t, p = stats.ttest_ind(a.values, b.values, axis=0, equal_var=True)",
         "    df = pd.DataFrame({'names': lcpm.columns, 'log2FC_pseudobulk': lfc.values,",
         "                       'pval': p, 'pvals_adj': bh(p)}).sort_values('pval')",
         "    df.to_csv(config.TABLE_DIR / f'pseudobulk_de_{sex.lower()}.csv', index=False)",
         "    pb_results[sex] = df",
         "    n_sig = int(((df.pvals_adj < 0.05) & (df.log2FC_pseudobulk.abs() > 1)).sum())",
         "    print(f'{sex}: {n_sig} significant at pseudobulk level (n=2 vs 2)')",
         "",
         "print()",
         "print('A small number here is EXPECTED. n=2 has almost no power.')",
         "print('The concordance check below is the informative part.')"),
    md("## Concordance with the cell-level result",
       "",
       "Interpretation:",
       "- **agreement > 80%** → the cell-level result is directionally trustworthy",
       "- **agreement ≈ 50%** → the signal is likely a pseudoreplication artefact"),
    code("for sex in ['Male', 'Female']:",
         "    cell = pd.read_csv(config.TABLE_DIR / f'de_global_{sex.lower()}_all.csv')",
         "    merged = cell.merge(pb_results[sex], on='names', suffixes=('_cell', '_pb'))",
         "    hits = merged[(merged.pvals_adj_cell < config.PADJ_THRESHOLD) &",
         "                  (merged.logfoldchanges.abs() > config.LOG2FC_THRESHOLD)]",
         "    if len(hits) < 5:",
         "        print(f'{sex}: too few hits'); continue",
         "",
         "    agree = (np.sign(hits.logfoldchanges) == np.sign(hits.log2FC_pseudobulk)).mean()",
         "    rho, prho = stats.spearmanr(hits.logfoldchanges, hits.log2FC_pseudobulk)",
         "    print(f'{sex}: {len(hits)} hits | direction agreement {agree:.1%} | rho={rho:.3f} (p={prho:.2e})')",
         "",
         "    fig, ax = plt.subplots(figsize=(5, 5))",
         "    ax.scatter(hits.logfoldchanges, hits.log2FC_pseudobulk, s=14, alpha=.7)",
         "    ax.axhline(0, lw=.5, c='k'); ax.axvline(0, lw=.5, c='k')",
         "    ax.set_xlabel('log2FC (cell-level Wilcoxon)')",
         "    ax.set_ylabel('log2FC (pseudobulk, n=2v2)')",
         "    ax.set_title(f'{sex}: rho = {rho:.2f}', fontsize=10)",
         "    fig.tight_layout()",
         "    fig.savefig(config.FIG_DIR / f'05b_pseudobulk_concordance_{sex.lower()}.png', dpi=150)",
         "    plt.show()"),
])

# ======================================================================
# 06 — ENRICHMENT
# ======================================================================
write("06_pathway_enrichment.ipynb", [
    md("# 06 — Pathway enrichment",
       "",
       "Equivalent to `scripts/06_pathway_enrichment.py`. Produces **Figure 5**, answers **RQ4**.",
       "",
       "A list of 400 gene names is not an answer. \"Cocaine remodels glutathione metabolism",
       "and Toll-like receptor signalling in glia\" is.",
       "",
       "## A bug in the project guide, worth knowing about",
       "",
       "The guide passes `gene_sets=['GO_Biological_Process_2023', 'KEGG_2021_Human']` with",
       "`organism='fly'`. Enrichr keeps **separate library catalogues per organism**, and",
       "those names belong to the Human catalogue. Requesting them in the Fly modality",
       "returns nothing useful — often silently. Flagging this in your peer review of",
       "another group would be a genuinely useful catch.",
       "",
       "Requires internet — Enrichr is a web API."),
    code(*HEADER),
    code("import gseapy as gp",
         "",
         "available = gp.get_library_name(organism=config.ENRICHR_ORGANISM)",
         "print(f'{len(available)} Fly libraries available. Sample:')",
         "for lib in available[:25]:",
         "    print(' ', lib)"),
    code("libraries = [l for l in config.ENRICHR_LIBRARIES_PREFERRED if l in available]",
         "",
         "for keyword in ['GO_Biological_Process', 'KEGG', 'GO_Molecular_Function']:",
         "    if not any(keyword in c for c in libraries):",
         "        match = [l for l in available if keyword in l]",
         "        if match:",
         "            libraries.append(sorted(match)[-1])",
         "",
         "print('Using:', libraries)"),
    md("## Helpers",
       "",
       "Splitting up- from down-regulated genes matters: mixing them lets an enriched term",
       "hide the fact that half its genes went one way and half the other, which is",
       "biologically meaningless."),
    code("def top_genes(df, direction, n=config.N_GENES_FOR_ENRICHMENT):",
         "    d = df[(df.pvals_adj < config.PADJ_THRESHOLD) &",
         "           (df.logfoldchanges.abs() > config.LOG2FC_THRESHOLD)]",
         "    d = d[d.logfoldchanges > 0] if direction == 'up' else d[d.logfoldchanges < 0]",
         "    return d.nsmallest(n, 'pvals_adj')['names'].tolist()",
         "",
         "def run_enrichment(genes, label):",
         "    genes = [g for g in dict.fromkeys(genes) if isinstance(g, str)]",
         "    if len(genes) < 5:",
         "        print(f'{label}: only {len(genes)} genes, skipping'); return None",
         "    try:",
         "        enr = gp.enrichr(gene_list=genes, gene_sets=libraries,",
         "                         organism=config.ENRICHR_ORGANISM, outdir=None)",
         "    except Exception as e:",
         "        print(f'{label}: Enrichr failed — {e}'); return None",
         "    res = enr.results.sort_values('Adjusted P-value')",
         "    res.to_csv(config.TABLE_DIR / f'enrichment_{label}.csv', index=False)",
         "    n_sig = int((res['Adjusted P-value'] < config.PADJ_THRESHOLD).sum())",
         "    print(f'{label}: {len(genes)} genes -> {n_sig} significant terms')",
         "    return res",
         "",
         "def barplot(res, label, n=12):",
         "    d = res.nsmallest(n, 'Adjusted P-value').iloc[::-1]",
         "    if d.empty: return",
         "    fig, ax = plt.subplots(figsize=(8, 0.36*len(d) + 1.6))",
         "    ax.barh(range(len(d)), -np.log10(d['Adjusted P-value'].clip(lower=1e-300)),",
         "            color='steelblue')",
         "    ax.set_yticks(range(len(d))); ax.set_yticklabels([t[:60] for t in d['Term']], fontsize=7)",
         "    ax.axvline(-np.log10(config.PADJ_THRESHOLD), ls='--', lw=.8, c='crimson')",
         "    ax.set_xlabel('-log10 adjusted p'); ax.set_title(label.replace('_',' '), fontsize=10)",
         "    fig.tight_layout()",
         "    fig.savefig(config.FIG_DIR / f'06_enrichment_{label}.png', dpi=150)",
         "    plt.show()"),
    md("## Global enrichment, per sex and direction"),
    code("for sex in ['male', 'female']:",
         "    df = pd.read_csv(config.TABLE_DIR / f'de_global_{sex}_all.csv')",
         "    for direction in ['up', 'down']:",
         "        label = f'{sex}_{direction}'",
         "        res = run_enrichment(top_genes(df, direction), label)",
         "        if res is not None:",
         "            display(res.head(10)[['Gene_set','Term','Adjusted P-value','Genes']])",
         "            barplot(res, label)"),
    md("## Per-cluster enrichment for the top responders",
       "",
       "This is where the paper's most interesting findings live — their C22 surface glia",
       "showed Notch signalling, GABA degradation, NF-κB immune pathways, and glutathione",
       "metabolism."),
    code("genes_df = pd.read_csv(config.TABLE_DIR / 'de_per_cluster_significant_genes.csv')",
         "summary = pd.read_csv(config.TABLE_DIR / 'de_per_cluster_summary.csv')",
         "",
         "top_clusters = (summary.dropna(subset=['n_sig'])",
         "                .groupby('cluster')['n_sig'].sum().nlargest(4).index.tolist())",
         "print('Top responders:', top_clusters)"),
    code("for cl in top_clusters:",
         "    for sex in ['Male', 'Female']:",
         "        sub = genes_df[(genes_df.cluster.astype(str) == str(cl)) & (genes_df.sex == sex)]",
         "        if len(sub) < 10: continue",
         "        genes = sub.nsmallest(config.N_GENES_FOR_ENRICHMENT, 'pvals_adj')['names'].tolist()",
         "        safe = str(cl).replace(' ', '-').replace('/', '-')",
         "        label = f'cluster_{safe}_{sex.lower()}'",
         "        res = run_enrichment(genes, label)",
         "        if res is not None:",
         "            barplot(res, label)"),
    md("## Compare with the paper",
       "",
       "Supplemental Table S10. Terms to look for:",
       "",
       "| Their cluster | Expected enrichment |",
       "|---|---|",
       "| C11, C20 — Kenyon cells | inositol phosphate metabolism, cAMP signalling |",
       "| C16 — unannotated | GPCR signalling, serotonin and glutamate receptors, Rhodopsin-like receptors |",
       "| C17 — astrocytes | glial metabolic support |",
       "| C22 — surface glia | Notch, GABA degradation, NF-κB, TLR signalling, glutathione metabolism |",
       "",
       "## A caveat for your report",
       "",
       "Enrichr's background is all annotated fly genes, but our DE test could only ever",
       "have found genes that survived QC and are expressed in brain. Using the full genome",
       "as background inflates significance for brain-expressed terms. Say so; do not",
       "present the adjusted p-values as exact."),
])

print("\nDone. Launch with:  uv run jupyter lab")
